level_key = {'VOC': ['Vocational','VET'],
             'DIP': ['Diploma', 'DIP','diploma'],
             'ADIP': ['Advanced Diploma'],
             'ADEG': ['Associate Degree'],
             'FUG': ['FD', 'FDs', 'FDEd', 'FdEd', 'FdA', 'FDA', 'FDArts', 'FDEng', 'FdSc', 'A.A.', 'A.S.',
                     'A.A.S', 'A.A.S.'],
             'Found': ['Foundation'],
             'BA': ['Bachelor', 'B.Trad.', 'BGInS', 'BAcc', 'BAFM', 'BAdmin', 'BAS', 'BAA', 'BASc', 'BASc/BEd',
                    'BArchSc', 'BAS', 'BA', 'BAS', 'BASc/BEd', 'BASc', 'BA/BComm', 'BA/BEd', 'BA/BEd/Dip', 'BA/LLB',
                    'BA/MA', 'BBRM', 'BBA', 'BBA/BA', 'BBA/BCS', 'BBA/BEd', 'BBA/BMath', 'BBA/BSc', 'BBE', 'BBTM',
                    'BDS', 'BCogSc', 'BComm', 'BCom', 'BCoMS', 'BCoSc', 'BCS', 'BComp', 'BCmp', 'BCFM', 'BDes', 'BDEM',
                    'BEcon', 'BEng', 'BEng&Mgt', 'BEngSoc', 'BESc', 'BEngTech', 'BEM', 'BESc', 'BESc/BEd', 'BES',
                    'BES/BEd', 'BFAA', 'BFA,BFA/BEd', 'BFS', 'BGBDA', 'BHP', 'BHSc', 'BHSc', 'BHS', 'BHS/BEd',
                    'BHum', 'BHK', 'BHRM', 'BID', 'BINF', 'BIT', 'BID', 'BIB', 'BJ', 'BJour', 'BJourn', 'BJHum',
                    'BKin', 'BK/BEd', 'BKI', 'BLA', 'BMOS', 'BMath', 'BMath/BEd', 'BMPD', 'BMRSc', 'BMSc', 'BMus',
                    'MusBac', 'BMusA', 'BMus/BEd', 'BMuth', 'BOR', 'BOR/BA', 'BOR/BEd', 'BOR/BSc', 'BPHE', 'BPhEd',
                    'BPHE/BEd', 'BPA', 'BPAPM', 'BPH', 'BRLS', 'BSc', 'BSc&Mgt', 'BSc/BASc', 'BSc/BComm', 'BSc/BEd',
                    'BSc(Eng)', 'BScFS', 'BScF', 'BSc(Kin)', 'BScN', 'BSocSc', 'BSW', 'BSE', 'BSM', 'BTech', 'BTh',
                    'BURPI', 'HND', 'HNC', 'iBA,iBA/BEd', 'iBBA', 'iBSc', 'iBSc/BEd', 'LLB', 'MEng', 'MChem',
                    'MPharm', 'MBiol', 'PCE', 'MBChB', 'DipHE', 'AS', 'BS', 'BSN', 'BSME', 'BSB', 'BSCH', 'BSA', 'BSEE',
                    'BLS', 'BSCE', 'BSCMPE', 'B.S.', 'B.A.', 'B.S.F.', 'B.M.', 'Major', 'Cognate', 'NSB', 'B.F.A.',
                    'Bachelor\'s', 'B.Sc.'],
             'BAH': ['Bachelor honours'],
             'GDIP': ['Graduate Diploma'],
             'GCERT': ['Graduate Certificate', 'PGCE ', 'PgC'],
             'PG': ['Postgraduate'],
             'MST': ['Master', 'M.A.', 'A.M.', 'MPhil', 'M.Phil.', 'MSc', 'M.S.', 'SM', 'MBA', 'M.B.A.', 'MSci',
                     'LLM', 'LL.M.', 'MMath', 'MPhys', 'MPsych', 'MRes' 'MSci', 'LMHC', 'MSEd', 'MS', 'MSE', 'MSECE',
                     'DNP', 'MSME', 'M.Ed.', 'M.Eng.', 'M.C.T.L.', 'M.I.P.', 'M.F.A', 'M.P.A.', 'M.P.P.', 'M.F.A.',
                     'M.A.L.S.', 'M.P.H.', 'M.A.T.', 'M.S.T.', 'M.S.W.', 'M.I.C.L.J.', 'M.S.W.',
                     'License', 'MDes', 'MRes', 'MMus', 'MEval', 'Master\'s', '2nd', 'M.Sc.', 'Pre-master'],
             'DOC': ['Doctor', 'Doctorate', 'ClinPsyD', 'D.D.', 'L.H.D.', 'Litt.D.', 'Ed.S.',
                     'LTD ', 'LL.D.', 'Mus.D.', 'S.D.', 'DPharm', 'Third'],
             'PHD': ['PhD', 'Ph.D.'],
             'Minor': ['Minor'],
             'SHORT COURSES': ['skill','short-course','statement-of-attainment'],
             'SEMINAR': ['Seminar'],
             'PRODEV': ['Tailor'],
             'CONF': ['Conference'],
             'HONS': ['Honours', 'Hons'],
             'CERTI':['Certificate I','certificate-i'],
             'CERTII': ['Certificate II','certificate-ii'],
             'CERTIII': ['Certificate III','certificate-iii'],
             'CERTIV': ['Certificate IV','certificate-iv'],
             'CERT': ['Victorian Certificate','victorian-certificate'],
             'ENG':['English','CELTA']
             }

faculty_key = {'Language & Literature': ['arabic', 'Beeld', 'Chinese', 'indology', 'Africana', 'Judaic', 'Japanese',
                                         'Narrative Preaching', 'Cultuurgeschiedenis', 'Comparative', ' Corinthians',
                                         ' Holy Spirit', 'Ephesians', ' Bible Study ', 'Missiology', 'German',
                                         'Italian', 'Swedish', 'philology', 'tesol', 'read', 'interpret', 'writing',
                                         'literature', 'languages', 'interpreting', 'language', 'sanskrit', 'thai',
                                         'vietnamese', 'yolngu', 'reading', 'translation', 'mandarchinese',
                                         'literatures', 'speakers', 'heroism', 'humanism', 'shakespeare', 'renaissance',
                                         'postcolonial', 'narratives', 'identity', 'streams', 'scriptwriting',
                                         'screenwriting', 'fiction', 'read', 'non-fiction', 'transcreation', 'subtitle',
                                         'subtitling', 'indian', 'mandar', 'character', 'phonetics', 'background',
                                         'aesol', 'translational', 'transcultural', 'purposes', 'local', 'urdu',
                                         'jewish', 'islamic', 'hispanic', 'tesol', 'story', 'children', 'hebrew',
                                         'spanish', 'Translator', 'irish', 'Gaeilge', 'logopaedics', 'rhaeto',
                                         'grzistik', 'nordistik', 'romance', 'bosnian', 'slovenian', 'tafl',
                                         'Logopedics', 'Coptic', 'Bookkeeping', 'letter', 'book', 'poetry'],
               'Education': ['childhood', 'Human Movement', 'Geschiedenis', 'think', 'education', 'teaching',
                             'numeracy', 'education', 'discipline', 'educational', 'schooling', 'junior', 'needs',
                             'ratep', 'views', 'learn', 'black', 'writers', 'race', 'years', 'disable', 'indigenous',
                             'prep', 'catholic', 'leading', 'difficulties', 'speaking', 'second', 'progressive',
                             'evaluation', 'parent', 'pgce', 'coordinator', 'primary', 'gifted', 'work', 'progress',
                             'baccalaureate', 'introduction', 'contexts', 'birth', 'five', 'expert', 'inclusive',
                             'curriculum', 'principal', 'preparation', 'accelerated', 'tertiary', 'senior',
                             'philosophies', 'student', 'students', 'academic', 'semiotics', 'intervention', 'ducier',
                             'managing', 'toddler', 'guidance', 'teach', 'visiting', 'education', 'salon', 'coach',
                             'integrationist', 'education', 'national'],
               'Science and Health Science': ['natural', 'ecotoxicology', 'Bioscience', 'Nanoscience', 'each',
                                              'Malting', 'BEC', 'ENHET', 'Reschem', 'Medical', 'biological',
                                              'orthoptic', 'dietistic', 'environmental', 'nanoscience',
                                              'Physiotheraphy', 'Linear', "A Levels", 'Chemistry', 'Narrative',
                                              'M.Pharm.', 'B.Pharm.(Hons.)', 'M.Sc.(Hons.)', 'bionanotechnology',
                                              'Suivi', 'seagriculture', 'health', 'marine', 'environment', 'podiatry',
                                              'nutrition', 'molecular', 'nhet', 'physician', 'genetics', 'dietetics',
                                              'classification', 'reproductive', 'microbiology', 'immunology',
                                              'nutritional', 'biochemistry', 'plant', 'zoology', 'botany', 'ecology',
                                              'animal', 'theoretical', 'water', 'forest', 'sustain', 'chiropractic',
                                              'analytical', 'conservation', 'wildlife', 'coastal', 'equine',
                                              'veterinary', 'mine', 'surveying', 'biological', 'conservation',
                                              'addiction', 'freshwater', 'evolution', 'organismal', 'hydrology',
                                              'ocean', 'biodiversity', 'team', 'clean', 'aquatic', 'ecosystems', 'gcp',
                                              'ich', 'regional', 'indigenous', 'cradle', 'grave', 'population',
                                              'coasts', 'astronomy', 'assyriology', 'catchments', 'geomorphology',
                                              'terrestrial', 'outdoor', 'atmospheric', 'developmental', 'drug',
                                              'formulation', 'resonance', 'geotechnical', 'meteorolgy',
                                              'pharmaceutical', 'chemical', 'psychiatry', 'statistical', 'proteomics',
                                              'anthropometry', 'physic', 'structure', 'leisure', 'function', 'geology',
                                              'geomatic', 'chemistry', 'kinetics', 'pedorthic', 'foot', 'care',
                                              'ecochemistry', 'evolutionary', 'laser', 'space', 'soil', 'sport',
                                              'experimental', 'disease', 'cell', 'weather', 'canine', 'fossil',
                                              'climate', 'energy', 'fuels', 'deposits', 'audiometry', 'physiological',
                                              'material', 'plants', 'oceanography', 'vision', 'life', 'agronomy',
                                              'neuro', 'archaeological', 'biophysics', 'geological', 'stata',
                                              'geospatial', 'measurement', 'statics', 'metabolism', 'monitoring',
                                              'fisheries', 'nautical', 'antarctic', 'wilderness', 'wellbeing',
                                              'nuclear', 'ear', 'rehabilitation', 'geostatistics', 'parasitology',
                                              'outreach', 'medicine', 'biology', 'functional', 'assessment', 'autism',
                                              'spectrum', 'disorders', 'psychotherapy', 'gerontology', 'audiology',
                                              'loss', 'grief', 'trauma', 'palliative', 'developing', 'strength',
                                              'service', 'suicide', 'suicidology', 'disaster', 'refugee', 'tropical',
                                              'hygiene', 'retrieval', 'bhet', 'biosecurity', 'preparedness',
                                              'communicable', 'protected', 'area', 'minerals', 'ageing', 'aged',
                                              'dietetic', 'ohs', 'ergonomics', 'promoting', 'spiritual',
                                              'radiopharmaceutical', 'midwifery', 'bioethics', 'chronic',
                                              'occupational', 'lifestyle', 'entomology', 'factors', 'hiv',
                                              'pharmacotherapy', 'therapy', 'biotech', 'geoinformatics', 'transport',
                                              'adaptation', 'biostatistics', 'bramind', 'genetic', 'disability',
                                              'ophthalmology', 'ophthalmic', 'qualitative', 'microscopy',
                                              'microanalysis', 'statistical modelling', 'extension maths', 'health',
                                              'biochem', 'optometry', 'radiation', 'reconstruction', 'paediatrics',
                                              'surgical', 'gender', 'professions', 'dissertation', 'anatomical',
                                              'neuropsychology', 'hydrogeology', 'surveillance', 'packaging',
                                              'emergency', 'diseases', 'food', 'alcohol', 'drugs', 'myotherapy',
                                              'fitness', 'psychology', 'bioinformatics', 'chemical', 'chemistry',
                                              'astrophysics', 'biology', 'physic', 'sci', 'cardiovascular',
                                              'meteorology', 'biosciences', 'bioscience', 'micropalaeontology',
                                              'toxicology', 'tomography', 'polymer', 'microtechnology',
                                              'nanostructures', 'chemist', 'stomatology', 'NGENTU', 'logopedia',
                                              'archeology', 'mental', 'geosciences', 'recycling', 'pediatric',
                                              'hydrography', 'gynaecological', 'Physiotherapie', 'wound',
                                              'biogeosciences', 'H\x9arakustik', 'Philosophie', 'Geophysics',
                                              'Paleontology', 'reflexology', 'kettlebells', 'circuit', 'yoga', 'sen',
                                              'trainer', 'behavioural', 'psycho'],
               'Creative Arts & Design & Music': ['design', '3D ', 'kino', 'reflective', 'Restructuring ', 'Batik',
                                                  'Classical', 'Landscaping', 'wool', 'hanging', 'classing',
                                                  'Serigraphy', 'Weaving', 'Product', 'Mets', 'Percussion', 'strings',
                                                  'tonmeister', 'woodwinds', 'organ', 'consort', 'brass', 'piano',
                                                  'aural', 'harp', 'guitar', 'ensemble', 'orchestra', 'accordion',
                                                  'Konst', 'creative', 'music', 'designs', 'fashion', 'studio',
                                                  'musicianship', 'musicology', 'jazz', 'popular', 'drama', 'jewellery',
                                                  'acting', 'performance', 'instrumental', 'vocal', 'composition',
                                                  'performing', 'transition', 'achievers', 'conducting',
                                                  'accompaniment', 'aural', 'musical', 'animating', 'direction',
                                                  'generated', 'imagery', 'interior', 'photo', 'Print', 'audio',
                                                  'player', 'moving', 'image', 'ethnomusicology', 'textile',
                                                  'merchandise', 'embroidery', 'clay', 'ceramic', 'branded',
                                                  'illustrative', 'dance', 'devices', 'choreography', 'cinema',
                                                  'storytelling', 'printmaking', 'fine', 'voice', 'ensemble',
                                                  'literacy', 'film', 'interaction', 'futures', 'beauty', 'playwriting',
                                                  'writings', 'directing', 'dramaturgy', 'producing', 'mmus', 'drawing',
                                                  'painting', 'improvisation', 'creativity', 'conservatorium',
                                                  'lighting', 'perception', 'materials', 'interactivation',
                                                  'accessories', 'decoration', 'hairdress', 'styling', 'art', 'beauty',
                                                  'cosmetic', 'hairstyling', 'perfformio', 'cyfarwyddo', 'eyelash',
                                                  'jewelry', 'manicure', 'cosmetology', 'esthetics', 'arts', 'Song',
                                                  'Ritual', 'Songwriting', 'BMusEd', 'BMusPerf', 'composing',
                                                  'Instrumental', 'mental', 'luxury', 'french art', 'its market',
                                                  'screen', 'makeup', 'baking', 'florist', 'tailor', 'Mesure',
                                                  'jewelery', 'leather', 'glass'],
               'Law': ['law', 'government', 'bar', 'tax', 'victimology', 'legal', 'juris', 'policy', 'jurisprudence',
                       'criminal', 'justice', 'criminology', 'investigation', 'deviance', 'prevention', 'advocacy',
                       'commincations', 'copyright', 'defamation', 'rights', 'intellectual', 'negotiation', 'patents',
                       'dispute', 'conveyancing', 'production', 'inquiry', 'intelligence', 'police', 'crime',
                       'policing', 'leases', 'undertaking', 'contract', 'pedagogy', 'ethics', 'ethical', 'action',
                       'regulation', 'lba', 'criminological', 'regulatory', 'comparative', 'juridical', 'migration',
                       'labour', 'private', 'corporations', 'miclaw', 'parliamentary', 'rotc', 'forensic', 'j.d',
                       'commercial', 'public affairs', 'diplomacy', 'arbitration', 'future', 'll.m.', 'argumentation',
                       'magister', 'legum', 'Legislative', 'paralegal'],
               'Medical and Nursing': ['biomedicine', 'herbal', 'Physiotherapist', 'hiv', 'nhet', 'Bioscience',
                                       'denturist', 'opticianry', 'Rheumatology', 'Gastroenterology', 'Cardiology',
                                       'Nephrology', 'Endocrinology', 'oral', 'physiotherapy', 'pathology',
                                       'biomedical', 'nursing', 'medical', 'surgery', 'accident', 'sonography',
                                       'paramedic', 'prehospital', 'pharmacy', 'dental', 'physiology', 'podiatric',
                                       'preclinical', 'paramedical', 'activity', 'diagnostics', 'pharmaceuticals',
                                       'evidence', 'cognitive', 'mind', 'anatomy', 'orthoptics', 'dementia',
                                       'prosthetics', 'orthotics', 'phatmaceutical', 'discovery', 'paramedicine',
                                       'dependency', 'haematology', 'transfusions', 'transplantation', 'cytopathology',
                                       'histopathology', 'radiations', 'osteopathy', 'osteopathic', 'kinesiology',
                                       'epidemiology', 'biomechanics', 'prescription', 'injury', 'motor', 'pharmacist',
                                       'instruction', 'coordination', 'dentistry', 'joint', 'diagnostic', 'injuries',
                                       'radiography', 'preventive', 'histology', 'context', 'neurobiology',
                                       'traditional', 'therapeutic', 'dermal', 'therapies', 'preliminary','health'
                                       'musculoskeletal', 'physiotherapy', 'specialisations', 'tissue', 'sexology',
                                       'critical', 'protection', 'diabetes', 'cancer', 'periodontology', 'acute',
                                       'initial', 'registration', 'overseas', 'nurses', 'specialised', 'embryology',
                                       'minimally', 'invasive', 'anaesthetics', 'recovery', 'burns', 'cardiac',
                                       'gerontological', 'pharmaceutics', 'infection', 'intensive', 'attachment',
                                       'oncology', 'orthopaedic', 'perioperative', 'renal', 'anaesthetic', 'apheresis',
                                       'hyperbaric', 'sleep', 'odontology', 'ultrasound', 'trials', 'breast',
                                       'cataract', 'refractive', 'restorative', 'orthodontics', 'prescribers',
                                       'paediatric', 'periodontics', 'prosthodontics', 'otolaryngology', 'm.ost',
                                       'immunity', 'pharmacology', 'inflammation', 'neurophysiology', 'stis', 'sexual',
                                       'metabolic', 'cardiothoracic', 'colorectal', 'endocrine', 'head', 'neck',
                                       'neurosurgery', 'otorhinolaryngology', 'reconstructive', 'outcomes',
                                       'transplant', 'upper', 'gastrointestinal', 'urology', 'vascular', 'endovascular',
                                       'complex', 'careageing', 'palliation', 'nurse', 'practitioner', 'medicine',
                                       'obstetrics', 'gynaecology', 'philosophypublic', 'endodontics', 'infectious',
                                       'dentistry', 'clinical', 'paraclinical', 'dentistry', 'medicine', 'biological',
                                       'medicine', 'clinical', 'medicine', 'philosophymedicine', 'testing', 'ambulance',
                                       'medication', 'histotechnician', 'women', 'personal support', 'clinician',
                                       'prescribing', 'spinal', 'allergy', 'neonatology', 'anxiety', 'CBT', 'surgeon',
                                       'Podiatrist', 'Psychologist', 'Podology', 'geriatrics', 'logopedics',
                                       'Acupuncture', 'Biomedizintechnik', 'rongo_', 'koroua', 'clinical'],
               'Mass Communication & Media': ['media', 'Informatica', 'medialogy', 'graphic', 'video', 'multimedia',
                                              'tv', 'broadcast', 'campaigns', 'communication', 'radio', 'theatre',
                                              'photography', 'mass', 'broadcasting', 'techniques', 'stakeholders',
                                              'reputation', 'cases', 'audience', 'photographic', 'imaging', 'effects',
                                              'motion', 'capture', 'photo', 'journalism', 'documentary', 'stop',
                                              'processing', 'immersive', 'intermediate', 'editing', 'convergent',
                                              'elite', 'printmedia', 'live', 'technical', 'film', 'theater',
                                              'Iriseoireacht'],
               'Architecture, Building & Planning': ['planning', 'carpentry', 'Serigraphy', 'Truck Driving',
                                                     'Architectural', 'Typography', 'Infographics', 'Museology',
                                                     'manufacturing', 'Textil', 'Keramik', 'quantity', 'architect',
                                                     'riba', 'timber', 'brick', 'construction', 'bricklaying',
                                                     'plaster', 'plumbing', 'creation', 'urban', 'building',
                                                     'architecture', 'built', 'airworthiness', 'acoustics',
                                                     'illumination', 'facilities', 'urbanism', 'surveying', 'city',
                                                     'prprac', 'town', 'merchandising', 'welding', 'monuments',
                                                     'ironworker', 'waka', 'carpenter', 'welder', 'cabinetry',
                                                     'renovation'],
               'Business & Commerce & Finance & Accounting': ['accounting', 'management', ' Joinery',
                                                              'Fiscale Economie', 'imagineering', 'Fiscale', 'ibs',
                                                              'open', 'origini', 'finanza', 'essec', 'mim', 'lse',
                                                              'cems', 'organization', 'NCC', 'ppe', 'finance',
                                                              'business', 'administration', 'global', 'arrange',
                                                              'commerce', 'resource', 'marketing', 'supply',
                                                              'financial', 'services', 'economics', 'corporate',
                                                              'sustainability', 'capital', 'market', 'math', 'spss',
                                                              'economic', 'proffesional', 'numer', 'entrepreneurship',
                                                              'property', 'banking', 'analytics', 'budget', 'taxation',
                                                              'bank', 'auditing', 'control', 'analysis', 'basel',
                                                              'statement', 'modelling', 'macroeconomic', 'logistics',
                                                              'advertising', 'trade', 'real', 'statistic', 'estate',
                                                              'promotion', 'enterprise', 'actuarial', 'strategy',
                                                              'specialist', 'accountancy', 'behavioural',
                                                              'econometrics', 'bus', 'insurance', 'margin',
                                                              'regression', 'reliability', 'keeping', 'innovation',
                                                              'vat', 'macroeconomics', 'aat', 'att', 'cfa', 'cfq',
                                                              'cisi', 'cpci', 'cpi', 'cppi', 'cta', 'fia', 'icaew',
                                                              'icas', 'icsa', 'imc', 'jieb', 'investments', 'money',
                                                              'portfolio', 'derivatives', 'foreign', 'exchange', 'cima',
                                                              'administrative', 'events', 'risk', 'resource', 'merger',
                                                              'growing', 'acquisition', 'economy', 'investment',
                                                              'manage', 'management', 'organisations', 'mortgage',
                                                              'conference', 'manager', 'commercer', 'organisation',
                                                              'quality', 'interdisciplinary', 'acca', 'logistic',
                                                              'algebra', 'strategic', 'international relation',
                                                              'nonprofit', 'process', 'frs', 'influencing',
                                                              'procurement', 'strategies', 'practising', 'negotiation',
                                                              'negotiating', 'purchasing', 'shipping', 'operations',
                                                              'treasury', 'investing', 'asset', 'actuary', 'accountant',
                                                              'm.b.a', 'manufacturing', 'retailing', 'commodities',
                                                              'celebrancy', 'MBA', 'specific', 'EnvEuro', 'branding',
                                                              'advertisement', 'marxism', 'zommertse', 'bba', 'BBA',
                                                              'consulting', 'economist', 'mba', 'sales', 'gestion',
                                                              'clerk', 'erp', 'supervision', 'ecommerce'],
               'Computer Science & Information Technology': ['information', 'industry', '.NET', 'Impit', 'ai',
                                                             'M.Sc.(Tech.)', 'routing', 'autodesk', 'adobe', 'mining',
                                                             'Thesis', 'algorithmic', 'procedural', 'programming',
                                                             'technology', 'digital', 'data', 'web', 'i.t.', 'security',
                                                             'computational', 'computer', 'microprocessors',
                                                             'intelligent', 'mechatronic', 'photonic', 'games',
                                                             'networking', 'internet', 'cybersecurity', 'entertainment',
                                                             'nanotechnology', 'network', 'graphics', 'interactivity',
                                                             'software', 'mobile', 'computing', 'application',
                                                             'mainframe', 'robotics', 'applications', 'cloud', 'infor',
                                                             'mation', 'networked', 'system', 'game', 'interface',
                                                             'scientific', 'remote', 'sensing', 'archives',
                                                             'recordkeeping', 'wireless', 'internetworking',
                                                             'informatics', 'records', 'bioinformatics', 'website',
                                                             'technical', 'cad', 'artificial', 'myob', 'integrated',
                                                             'technology', 'IC Design', 'integrated', 'IoT',
                                                             'interactive', 'technologies', 'eletronics minor',
                                                             'Electronics', 'IT', 'applied computer science', 'ITT',
                                                             'it', 'cisco', 'Cyberfraude', 'Cyberfraude'],
               'Engineering': ['engineering', 'M.E.', 'bioengineering', 'B.E.(Hons.)', 'bngineer', 'research',
                               'Aircraft', 'mechanical', 'metallurgical', 'renewable', 'municipal', 'transportation',
                               'extractive', 'metallurgy', 'petroleum', 'civil', 'electical', 'Mechanics', 'motorsport',
                               'robotic', 'microelectronic', 'mechatronics', 'infrastructure', 'instrumentation',
                               'mechatronic', 'geospacial', 'photovoltaics', 'solar', 'aeronautical', 'structures',
                               'electrical', 'powercraft', 'decommissioning', 'utility', 'subsea', 'mapping',
                               'intrumentation', 'automation', 'pollution', 'bioresource', 'imeche', 'biochemical',
                               'autonomous', 'fluids', 'geomechanical', 'naval', 'fire', 'sciencce', 'ventilation',
                               'photov', 'innovative', 'vehicle', 'oil', 'gas', 'efficient', 'fabrication',
                               'specialising', 'units', 'mechanical', 'equipment', 'graphene', 'cybernetics',
                               'mechanics', 'machining', 'lineworker', 'aerodynamics', 'electrochemistry', 'engineer',
                               'industrial', 'mobility', 'geodesy', 'medtech', 'Mechanical', 'Motosport', 'automotive',
                               'pneumatics', 'professional', 'Maschinenbau', 'Mechatronik', 'mechanic', 'forklift',
                               'repair', 'electrician', 'locksmith', 'technician', 'plumber', 'pipefitter'],
               'Humanities and Social Science': ['islander', 'exercise', 'tears', 'violence', 'childhood', 'behaviour',
                                                 'needs', 'babies', 'stress', 'catastrophe', 'imer', 'georgian',
                                                 'freedom', 'hunger', 'history', 'literary', 'philosophy', 'leader',
                                                 'heritage', 'humanities', 'communities', 'women', 'perspectives',
                                                 'social', 'counter', 'terrorism', 'theology', 'globalisation',
                                                 'E-Secretaryship', 'Governance', 'Sociomy', 'european', 'latamerican',
                                                 'middle', 'eastern', 'central', 'american', 'french', 'greek',
                                                 'italian', 'spanish', 'modern', 'lote', 'anthropology', 'german',
                                                 'indonesian', 'aborigin', 'korean', 'italian', 'culture',
                                                 'curatorship', 'ancient', 'archaeology', 'religions', 'ceramics',
                                                 'societies', 'europe', 'furniture', 'sexuality', 'glass', 'gold',
                                                 'silversmithing', 'latin', 'linguistics', 'pacific', 'peace',
                                                 'persian', 'sculpture', 'textiles', 'icelandic', 'behavior',
                                                 'sociology', 'psychological', 'humanitarian', 'knowledge', 'biblical',
                                                 'systematic', 'swedish', 'church', 'practical', 'theological',
                                                 'behaviour', 'across', 'lifespan', 'forms', 'career', 'power',
                                                 'protest', 'globalising', 'world', 'place', 'near', 'east', 'artefact',
                                                 'slovak', 'hebrew', 'egypt', 'ukrainian', 'place', 'czech',
                                                 'bulgarian', 'finnish', 'hungarian', 'cultural', 'historical',
                                                 'geography', 'geographic', 'exploration', 'interpersonal', 'working',
                                                 'child', 'approaches', 'democratisation', 'state', 'union',
                                                 'managerial', 'cost', 'conversation', 'converse', 'feedback',
                                                 'benefit', 'hr', 'century', 'relation', 'canadian', 'intercultural',
                                                 'presentation', 'norwegian', 'areas', 'cities', 'dutch', 'rise',
                                                 'pasts', 'future', 'gaelic', 'norwegian', 'diversity', 'speech',
                                                 'hearing', 'chinese', 'hellenic', 'scandinavian', 'politic', 'greece',
                                                 'rome', 'late', 'labrador', 'antiquity', 'croatian', 'development',
                                                 'competence', 'philosophical', 'skill', 'success', 'transnational',
                                                 'situated', 'francophone', 'stage', 'folk', 'polish', 'viking',
                                                 'russian', 'cultures', 'histories', 'danish', 'religious', 'religion',
                                                 'counterterrorism', 'young', 'people', 'healing', 'psychopshysiology',
                                                 'asian', 'affair', 'nationalism', 'classic', 'consumer', 'americas',
                                                 'scottish', 'portuguese', 'counselling', 'family', 'community',
                                                 'confidence', 'influencing', 'museum', 'ministry', 'engagement',
                                                 'resilience', 'training', 'citizenship', 'illustration',
                                                 'psycholigical', 'honor', 'psychophysiology', 'african', 'practices',
                                                 'sound', 'animation', 'thought', 'participatory', 'curatorial',
                                                 'japanese', 'forestry', 'islam', 'qualifying', 'archaeology',
                                                 'ethnology', 'chaplaincy', 'divinity', 'translating', 'hazards',
                                                 'curating', 'crosscultural', 'publishing', 'pastoral', 'difference',
                                                 'combined', 'adult', 'personnel', 'vocational', 'transformations',
                                                 'basic', 'linguistic', 'hindi', 'issues', 'buddhist', 'confident',
                                                 'children', 'celtic', 'germanic', 'civilisation', 'medieval', 'coach',
                                                 'consultant', 'partner', 'abroad', 'sociology', 'children', 'polar',
                                                 'slavonic', 'genocide', 'conflict', 'sinology', 'nordic', 'counseling',
                                                 'curation', 'surveys', 'demography', 'Methodology', 'anthropologists',
                                                 'orientalistics', 'change', 'civic', 'welfare', 'Border', 'cultural',
                                                 'Socio-cultural', 'caucasian', 'recruitment'],
               'Tourism and Hotel Management': ['hospitality', 'tourism', 'tour', 'ecotourism', 'recreation', 'revenue',
                                                'resort', 'convention', 'festival', 'visitor', 'travel', 'resource',
                                                'tourist', 'hotel'],
               'Agriculture': ['agriculture', 'Parks ', 'crop', 'aquaculture', 'sutainability', 'agri', 'conseration',
                               'agrifood', 'livestock', 'horticulture', 'poultry', 'farming', 'viticulture', 'oenology',
                               'drylagricultural', 'ecosystem', 'bushfire', 'roofs', 'walls', 'vet', 'breeding',
                               'dairy', 'limnology', 'horticulture', 'gardener'],
               'Foundation': ['foundation', 'refresher', 'pathway'],
               'English': ['english', 'EAL', 'test', 'ieal', 'beginner', 'elementary', 'ielts', 'spoken', 'written',
                           'spoken', 'proficiency'],
               'Aviation': ['aviation', 'Eng lish', 'aerospace', 'aeroplane', 'flight', 'aeronautics'],
               'Culinary': ['chef', ' Baking', 'enology', 'culinary', 'cake', 'pastry', 'cook', 'wine', 'beverage',
                            'patisserie', 'Taster', 'cookery', 'butchery'],
               'Culture': ['japanese'],
               'Behaviourial': ['Praxeology', 'Orthopedagogy']}
