level_key = {'VOC': ['Vocational','VET'],
             'DIP': ['Diploma', 'DIP'],
             'ADIP': ['Advanced Diploma'],
             'ADEG': ['Associate Degree'],
             'FUG': ['FD', 'FDs', 'FDEd', 'FdEd', 'FdA', 'FDA', 'FDArts', 'FDEng', 'FdSc', 'A.A.', 'A.S.',
                     'A.A.S', 'A.A.S.'],
             'Found': ['Foundation'],
             'BA': ['Bachelor', 'B.Trad.', 'BGInS', 'BAcc', 'BAFM', 'BAdmin', 'BAS', 'BAA', 'BASc', 'BASc/BEd',
                    'BArchSc', 'BAS', 'BA', 'BAS', 'BASc/BEd', 'BASc', 'BA/BComm', 'BA/BEd', 'BA/BEd/Dip', 'BA/LLB',
                    'BA/MA', 'BBRM', 'BBA', 'BBA/BA', 'BBA/BCS', 'BBA/BEd', 'BBA/BMath', 'BBA/BSc', 'BBE', 'BBTM',
                    'BDS', 'BCogSc', 'BComm', 'BCom', 'BCoMS', 'BCoSc', 'BCS', 'BComp', 'BCmp', 'BCFM', 'BDes', 'BDEM',
                    'BEcon', 'BEng', 'BEng&Mgt', 'BEngSoc', 'BESc', 'BEngTech', 'BEM', 'BESc', 'BESc/BEd', 'BES',
                    'BES/BEd', 'BFAA', 'BFA,BFA/BEd', 'BFS', 'BGBDA', 'BHP', 'BHSc', 'BHSc', 'BHS', 'BHS/BEd',
                    'BHum', 'BHK', 'BHRM', 'BID', 'BINF', 'BIT', 'BID', 'BIB', 'BJ', 'BJour', 'BJourn', 'BJHum',
                    'BKin', 'BK/BEd', 'BKI', 'BLA', 'BMOS', 'BMath', 'BMath/BEd', 'BMPD', 'BMRSc', 'BMSc', 'BMus',
                    'MusBac', 'BMusA', 'BMus/BEd', 'BMuth', 'BOR', 'BOR/BA', 'BOR/BEd', 'BOR/BSc', 'BPHE', 'BPhEd',
                    'BPHE/BEd', 'BPA', 'BPAPM', 'BPH', 'BRLS', 'BSc', 'BSc&Mgt', 'BSc/BASc', 'BSc/BComm', 'BSc/BEd',
                    'BSc(Eng)', 'BScFS', 'BScF', 'BSc(Kin)', 'BScN', 'BSocSc', 'BSW', 'BSE', 'BSM', 'BTech', 'BTh',
                    'BURPI', 'HND', 'HNC', 'iBA,iBA/BEd', 'iBBA', 'iBSc', 'iBSc/BEd', 'LLB', 'MEng', 'MChem',
                    'MPharm', 'MBiol', 'PCE', 'MBChB', 'DipHE', 'AS', 'BS', 'BSN', 'BSME', 'BSB', 'BSCH', 'BSA', 'BSEE',
                    'BLS', 'BSCE', 'BSCMPE', 'B.S.', 'B.A.', 'B.S.F.', 'B.M.', 'Major', 'Cognate', 'NSB', 'B.F.A.',
                    'Bachelor\'s', 'B.Sc.'],
             'BAH': ['Bachelor honours'],
             'GDIP': ['Graduate Diploma'],
             'GCERT': ['Graduate Certificate', 'PGCE ', 'PgC'],
             'PG': ['Postgraduate'],
             'MST': ['Master', 'MA', 'M.A.', 'A.M.', 'MPhil', 'M.Phil.', 'MSc', 'M.S.', 'SM', 'MBA', 'M.B.A.', 'MSci',
                     'LLM', 'LL.M.', 'MMath', 'MPhys', 'MPsych', 'MRes' 'MSci', 'LMHC', 'MSEd', 'MS', 'MSE', 'MSECE',
                     'DNP', 'MSME', 'M.Ed.', 'M.Eng.', 'M.C.T.L.', 'M.I.P.', 'M.F.A', 'M.P.A.', 'M.P.P.', 'M.F.A.',
                     'M.A.L.S.', 'M.P.H.', 'M.A.T.', 'M.S.T.', 'M.S.W.', 'M.I.C.L.J.', 'M.S.W.',
                     'License', 'MDes', 'MRes', 'MMus', 'MEval', 'Master\'s', '2nd', 'M.Sc.', 'Pre-master'],
             'DOC': ['Doctor', 'Doctorate', 'ClinPsyD', 'D.D.', 'L.H.D.', 'Litt.D.', 'Ed.S.',
                     'LTD ', 'LL.D.', 'Mus.D.', 'S.D.', 'DPharm', 'Third'],
             'PHD': ['PhD', 'Ph.D.'],
             'Minor': ['Minor'],
             'SHORT COURSES': ['Short', 'Course','Print Awareness','Skills Uplift','Construction Induction Card',
                               'Registered Electrical','Introduction to Programmable Logic Controllers',
                               'Testing and Tagging',' Testing Fundamentals','Raspberry Pi','Readiness Assessment',
                               'Construction Wiring and Mandatory Testing','Tutorial','Inventor','AutoCAD',
                               'Install','Operate','Grid','Skill','Stand Alone Power Systems','Low Voltage Rescue and CPR',
                               'First Aid'],
             'SEMINAR': ['Seminar'],
             'PRODEV': ['Tailor'],
             'CONF': ['Conference'],
             'HONS': ['Honours', 'Hons'],
             'CERTI':['Certificate I'],
             'CERTII': ['Certificate II'],
             'CERTIII': ['Certificate III'],
             'CERTIV': ['Certificate IV'],
             'CERT': ['Victorian Certificate'],
             'ENG':['English','CELTA']
             }

faculty_key = {
    'Business & Law': [''],
    'Education & Arts': [''],
    'Engineering & Built Environment': [''],
    'Health & Medicine': [''],
    'Science': ['natural', 'ecotoxicology', 'Bioscience', 'Nanoscience', 'each', 'Malting', 'BEC', 'ENHET', 'Reschem', 'Medical', 'biological', 'orthoptic', 'dietistic', 'environmental', 'nanoscience', 'Physiotheraphy', 'Linear', "A Levels", 'Chemistry', 'Narrative', 'M.Pharm.', 'B.Pharm.(Hons.)', 'M.Sc.(Hons.)', 'bionanotechnology', 'Suivi', 'seagriculture', 'health', 'marine', 'environment', 'podiatry', 'nutrition', 'molecular', 'nhet', 'physician', 'genetics', 'dietetics', 'classification', 'reproductive', 'microbiology', 'immunology', 'nutritional', 'biochemistry', 'plant', 'zoology', 'botany', 'ecology', 'animal', 'theoretical', 'water', 'forest', 'sustain', 'chiropractic', 'analytical', 'conservation', 'wildlife', 'coastal', 'equine', 'veterinary', 'mine', 'surveying', 'biological', 'conservation', 'addiction', 'freshwater', 'evolution', 'organismal', 'hydrology', 'ocean', 'biodiversity', 'team', 'clean', 'aquatic', 'ecosystems', 'gcp', 'ich', 'regional', 'indigenous', 'cradle', 'grave', 'population', 'coasts', 'astronomy', 'assyriology', 'catchments', 'geomorphology', 'terrestrial', 'outdoor', 'atmospheric', 'developmental', 'drug', 'formulation', 'resonance', 'geotechnical', 'meteorolgy', 'pharmaceutical', 'chemical', 'psychiatry', 'statistical', 'proteomics', 'anthropometry', 'physic', 'structure', 'leisure', 'function', 'geology', 'geomatic', 'chemistry', 'kinetics', 'pedorthic', 'foot', 'care', 'ecochemistry', 'evolutionary', 'laser', 'space', 'soil', 'sport', 'experimental', 'disease', 'cell', 'weather', 'canine', 'fossil', 'climate', 'energy', 'fuels', 'deposits', 'audiometry', 'physiological', 'material', 'plants', 'oceanography', 'vision', 'life', 'agronomy', 'neuro', 'archaeological', 'biophysics', 'geological', 'stata', 'geospatial', 'measurement', 'statics', 'metabolism', 'monitoring', 'fisheries', 'nautical', 'antarctic', 'wilderness', 'wellbeing', 'nuclear', 'ear', 'rehabilitation', 'geostatistics', 'parasitology', 'outreach', 'medicine', 'biology', 'functional', 'assessment', 'autism', 'spectrum', 'disorders', 'psychotherapy', 'gerontology', 'audiology', 'loss', 'grief', 'trauma', 'palliative', 'developing', 'strength', 'service', 'suicide', 'suicidology', 'disaster', 'refugee', 'tropical', 'hygiene', 'retrieval', 'bhet', 'biosecurity', 'preparedness', 'communicable', 'protected', 'area', 'minerals', 'ageing', 'aged', 'dietetic', 'ohs', 'ergonomics', 'promoting', 'spiritual', 'radiopharmaceutical', 'midwifery', 'bioethics', 'chronic', 'occupational', 'lifestyle', 'entomology', 'factors', 'hiv', 'pharmacotherapy', 'therapy', 'biotech', 'geoinformatics', 'transport', 'adaptation', 'biostatistics', 'bramind', 'genetic', 'disability', 'ophthalmology', 'ophthalmic', 'qualitative', 'microscopy', 'microanalysis', 'statistical modelling', 'extension maths', 'health', 'biochem', 'optometry', 'radiation', 'reconstruction', 'paediatrics', 'surgical', 'gender', 'professions', 'dissertation', 'anatomical', 'neuropsychology', 'hydrogeology', 'surveillance', 'packaging', 'emergency', 'diseases', 'food', 'alcohol', 'drugs', 'myotherapy', 'fitness', 'psychology', 'bioinformatics', 'chemical', 'chemistry', 'astrophysics', 'biology', 'physic', 'sci', 'cardiovascular', 'meteorology', 'biosciences', 'bioscience', 'micropalaeontology', 'toxicology', 'tomography', 'polymer', 'microtechnology', 'nanostructures', 'chemist', 'stomatology', 'NGENTU', 'logopedia', 'archeology', 'mental', 'geosciences', 'recycling', 'pediatric', 'hydrography', 'gynaecological', 'Physiotherapie', 'wound', 'biogeosciences', 'H\x9arakustik', 'Philosophie', 'Geophysics', 'Paleontology', 'reflexology', 'kettlebells', 'circuit', 'yoga', 'sen', 'trainer', 'behavioural', 'psycho'],
    'Pathways and Academic Learning Support Centre': ['yapug','open foundation', 'newstep'],
    'Others': ['indigenous']
}
